#+author: 班级：临床204班 姓名：张昊 学号：4203120507
#+title: 浅谈皮肤移植在烧伤病人中的运用

*摘要* ：狭义的烧伤是指因热力所造成的组织损伤，一般发生在皮肤、肌肉及皮下组织中，有数据显示，我国烧伤发生率约为1%，其中，多数患者为深度烧伤，以皮肤、肌肉及骨骼的持久性损伤为主要临床表现。烧伤早期外科手术治疗中包括皮肤移植。
本文通过查阅相关文献，简述皮肤移植在烧伤病人中的应用。

*关键词* ：烧伤，皮肤移植

*正文*

* 基本原理
  
  I度烧伤仅伤及表皮浅层，生发层健在，无需特殊处理，能自行消退。
  
  小面积浅II度烧伤，伤及表皮的生发层和真皮乳头层。如无感染，创面可于1～2周内愈合；若有感染，勤换敷料，清除脓性分泌物，保持创面清洁，多能自行愈合。
  
  深度烧伤伤及真皮乳头层以下，可深达骨骼或内脏。此时除使用正确的抗菌药物外，因其由开始的凝固型坏死经液化到与健康组织分离，需要两到三周，在这一过程中，随时存在侵入性感染风险，因此多主张采用积极的手术治疗，包括早期切痂或削痂，并立即进行皮肤移植。
  
  早期外科手术能减少全身性感染发病率，降低脏器并发症，提高大面积烧伤的治愈率，并缩短住院日。
  
  其中皮肤移植主要用于修复皮肤与其下组织缺损，以及矫正外部畸形等。自体皮肤移植常用两种方法。
  
** 游离皮瓣移植
   
   根据切取皮片的厚度可分为：
   1. 刃厚皮片：含表皮和真皮乳头层，是最薄的一种皮片，移植容易存活，但存活后易收缩，耐磨性差。
   2. 中厚皮片：包括表皮和真皮的二分之一到三分之一，弹性和耐磨性均较刃厚皮片为佳，适用于关节、手背等功能部位。
   3. 全厚皮片：包括皮肤的全层。存活后色泽、弹性、功能接近正常皮肤、耐磨性好。适用于手掌、足底与面颈部的创面修复。

** 皮瓣移植

   适用于修复软组织严重缺损，肌腱、神经、血管、骨质裸露，创面血液循环差的深度创面，特别是功能部位。
   分为两类：
   1. 带蒂皮瓣：由一带有血液供应的皮肤和皮下组织所形成，除蒂部与供皮区相连接外，其他三面均与供处分离。此皮瓣可用于
      修复临近或较远处的组织缺损。皮瓣缝合固定于缺损处后，蒂部仍与供处连接，暂时保证皮瓣的血液供应，待皮瓣与创底
      建立确实的血液循环后（一般需三到四周），再予断蒂。
   2. 游离皮瓣移植：将一块完全游离的自体皮瓣，通过显微外科手术，将皮瓣的静脉、动脉与缺损区的静动脉吻合，
      以保证该皮瓣的血液供应与静脉回流。常用于严重损毁性烧伤软组织严重缺损的创面，无法采用局部带蒂皮瓣修复者。

** 大面积III度烧伤的植皮术

   由于存在自体供皮区严重不足的问题，一般采用自体微粒植皮和大张异体皮开洞嵌植自体皮等方法。异体或异种皮虽会被排斥
   但可起到过渡性覆盖创面的作用。
   1. 自体微粒植皮：将自体皮片用剪刀或碎皮机剪成1毫米以下的微小皮粒，置于等渗盐水中做成悬液，均匀涂抹在异体（种）皮
      真皮面，再植于切痂创面，自体皮即在异体（种）皮保护下生长并扩展融合成片。
   2. 大张异体皮开洞嵌植自体皮：适用于广泛深度烧伤大面积切削痂后的创面。先将大张开洞的异体（种）皮移植于已切削痂的
      创面，缝合包扎。两天后观察，若存活，则于开洞处嵌植点状自体皮，待异体（种）皮溶解脱落时，自体皮即已扩展覆盖创面。
      

* 临床应用进展

** EDB治疗

深度烧伤（DB）面积超过40%总体表面积 (total body surface area, TBSA) 者, 病情复杂, 供皮区相对缺乏, 如何及时、准确地施治, 直接影响患者病情变化及转归。
业已证实，烧伤早期切除植皮即伤后尽早去除坏死及炎症组织并有效封闭创面，能有效减少感染性并发症、缩短住院时间、降低病死率，是改善大面积深度烧伤(extensive deep burns，EDB) 生存及后果的关键技术。

DB切除后形成一开放创面，必须被及时封闭并最终修复。性能可靠并常用的暂时性皮肤移植物为冷藏异体皮和新鲜异种皮(小猪皮)。无活性类生物敷料封闭性差、易感染并可致创面加深，应慎用，但对保留薄层变性真皮创面可一定面积使用。
EDB供皮区缺乏，常用的永久性皮肤移植物为自体刃厚皮，常用的封闭与修复技术有混合移植、微粒皮移植、皮浆移植、网状植皮、Meek 植皮和小皮片移植，其目的都是利用有限的供皮区来修复大面积创面。
这些材料和方法各有优缺点，应根据患者全身病情、受皮区血运、自体供皮情况和专业经验、材料储备、设备条件，以简便易行、效果确实为目的，酌情加以选择。
[ @Song2017 ]


** 瘢痕缓解

   瘢痕组织切除术是临床应用较多的治疗手段，
能够对瘢痕进行清除，其应用范围较广，适用于身
体不同部位、不同类型的瘢痕，且在手术过程中无
须进行全身麻醉，有着更好的安全性，手术创伤更
小，更有利于患者术后恢复。中厚皮肤移植术
是一种将自身皮肤进行移植的治疗手段，中厚皮有
着耐摩擦、质地柔软、术后存活率高等特点，能够
对皮肤过紧、活动受限等症状进行有效缓解，提高
创面的美观度，在深度烧伤患者治疗中使用较多，
应用效果较好。

研究表明[ @Liu2022 ]，常规瘢痕切除术与瘢痕切除术联合中厚皮肤移植术两组术后厚度、柔软
度、色泽、血管分布评分均明显下降（P<0.05），后者
厚度、柔软度、色泽、血管分布评分均明显低
于前者（P<0.05），提示瘢痕组织切除术联合中厚
皮肤移植术较常规治疗方式相比能够更好降低瘢痕
评分。


* 讨论

  在我国，烧伤发生率较高，是临床常见的意外
伤害之一，其发生率仅次于车祸，而深度烧伤在烧
伤患者中所占比例较重。深度烧伤伤及患者真皮
层，因皮肤受损较为严重，患者恢复较慢，且容易
形成瘢痕，对患者肢体功能与美观度造成不利影响，
可严重降低患者生活质量。常规药物治疗与功能
锻炼虽能在一定程度上对临床症状进行缓解，但改
善效果不佳，不能有效满足患者康复需求。植皮术可以在
保护创面、消除瘢痕等方面有效提高深度烧伤的疗效及病人的生活质量，
但大面积深度烧伤手术治疗面临自体皮“供”和“求”的矛盾，这也是目前研究的方向之一。


* References
